<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <RuntimeFrameworkVersion>8.0.29</RuntimeFrameworkVersion>
    <TargetLatestRuntimePatch>false</TargetLatestRuntimePatch>
    <RollForward>LatestPatch</RollForward>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <AssemblyName>BitwardenAgentCredentialBridgeHelper</AssemblyName>
    <RootNamespace>BitwardenAgentCredentialBridgeHelper</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
